namespace CaffeMeoo
{
    partial class AdminProduct
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminProduct));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.AdminUpdateProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminDeleteProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminAddProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AdminFillEmployeeGender = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductAvailable = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductType = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminFillProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.AdminCheckProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // dataGridView1
            // 
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(190, 199);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.Size = new System.Drawing.Size(421, 362);
            this.dataGridView1.TabIndex = 69;
            // 
            // AdminUpdateProduct
            // 
            this.AdminUpdateProduct.AllowAnimations = true;
            this.AdminUpdateProduct.AllowMouseEffects = true;
            this.AdminUpdateProduct.AllowToggling = false;
            this.AdminUpdateProduct.AnimationSpeed = 200;
            this.AdminUpdateProduct.AutoGenerateColors = false;
            this.AdminUpdateProduct.AutoRoundBorders = false;
            this.AdminUpdateProduct.AutoSizeLeftIcon = true;
            this.AdminUpdateProduct.AutoSizeRightIcon = true;
            this.AdminUpdateProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminUpdateProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminUpdateProduct.BackgroundImage")));
            this.AdminUpdateProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.ButtonText = "Update";
            this.AdminUpdateProduct.ButtonTextMarginLeft = 0;
            this.AdminUpdateProduct.ColorContrastOnClick = 45;
            this.AdminUpdateProduct.ColorContrastOnHover = 45;
            this.AdminUpdateProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.AdminUpdateProduct.CustomizableEdges = borderEdges5;
            this.AdminUpdateProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminUpdateProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminUpdateProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminUpdateProduct.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.IconLeft = null;
            this.AdminUpdateProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminUpdateProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminUpdateProduct.IconMarginLeft = 11;
            this.AdminUpdateProduct.IconPadding = 10;
            this.AdminUpdateProduct.IconRight = null;
            this.AdminUpdateProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminUpdateProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminUpdateProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminUpdateProduct.IconSize = 25;
            this.AdminUpdateProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.IdleBorderRadius = 37;
            this.AdminUpdateProduct.IdleBorderThickness = 1;
            this.AdminUpdateProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.IdleIconLeftImage = null;
            this.AdminUpdateProduct.IdleIconRightImage = null;
            this.AdminUpdateProduct.IndicateFocus = false;
            this.AdminUpdateProduct.Location = new System.Drawing.Point(646, 506);
            this.AdminUpdateProduct.Name = "AdminUpdateProduct";
            this.AdminUpdateProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminUpdateProduct.OnDisabledState.BorderRadius = 37;
            this.AdminUpdateProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnDisabledState.BorderThickness = 1;
            this.AdminUpdateProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminUpdateProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminUpdateProduct.OnDisabledState.IconLeftImage = null;
            this.AdminUpdateProduct.OnDisabledState.IconRightImage = null;
            this.AdminUpdateProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.onHoverState.BorderRadius = 37;
            this.AdminUpdateProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.onHoverState.BorderThickness = 1;
            this.AdminUpdateProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminUpdateProduct.onHoverState.IconLeftImage = null;
            this.AdminUpdateProduct.onHoverState.IconRightImage = null;
            this.AdminUpdateProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnIdleState.BorderRadius = 37;
            this.AdminUpdateProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnIdleState.BorderThickness = 1;
            this.AdminUpdateProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.OnIdleState.IconLeftImage = null;
            this.AdminUpdateProduct.OnIdleState.IconRightImage = null;
            this.AdminUpdateProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnPressedState.BorderRadius = 37;
            this.AdminUpdateProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminUpdateProduct.OnPressedState.BorderThickness = 1;
            this.AdminUpdateProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminUpdateProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminUpdateProduct.OnPressedState.IconLeftImage = null;
            this.AdminUpdateProduct.OnPressedState.IconRightImage = null;
            this.AdminUpdateProduct.Size = new System.Drawing.Size(201, 36);
            this.AdminUpdateProduct.TabIndex = 68;
            this.AdminUpdateProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminUpdateProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminUpdateProduct.TextMarginLeft = 0;
            this.AdminUpdateProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminUpdateProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminDeleteProduct
            // 
            this.AdminDeleteProduct.AllowAnimations = true;
            this.AdminDeleteProduct.AllowMouseEffects = true;
            this.AdminDeleteProduct.AllowToggling = false;
            this.AdminDeleteProduct.AnimationSpeed = 200;
            this.AdminDeleteProduct.AutoGenerateColors = false;
            this.AdminDeleteProduct.AutoRoundBorders = false;
            this.AdminDeleteProduct.AutoSizeLeftIcon = true;
            this.AdminDeleteProduct.AutoSizeRightIcon = true;
            this.AdminDeleteProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminDeleteProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminDeleteProduct.BackgroundImage")));
            this.AdminDeleteProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.ButtonText = "DELETE";
            this.AdminDeleteProduct.ButtonTextMarginLeft = 0;
            this.AdminDeleteProduct.ColorContrastOnClick = 45;
            this.AdminDeleteProduct.ColorContrastOnHover = 45;
            this.AdminDeleteProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.AdminDeleteProduct.CustomizableEdges = borderEdges6;
            this.AdminDeleteProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminDeleteProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminDeleteProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminDeleteProduct.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.IconLeft = null;
            this.AdminDeleteProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminDeleteProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminDeleteProduct.IconMarginLeft = 11;
            this.AdminDeleteProduct.IconPadding = 10;
            this.AdminDeleteProduct.IconRight = null;
            this.AdminDeleteProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminDeleteProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminDeleteProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminDeleteProduct.IconSize = 25;
            this.AdminDeleteProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.IdleBorderRadius = 37;
            this.AdminDeleteProduct.IdleBorderThickness = 1;
            this.AdminDeleteProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.IdleIconLeftImage = null;
            this.AdminDeleteProduct.IdleIconRightImage = null;
            this.AdminDeleteProduct.IndicateFocus = false;
            this.AdminDeleteProduct.Location = new System.Drawing.Point(762, 467);
            this.AdminDeleteProduct.Name = "AdminDeleteProduct";
            this.AdminDeleteProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminDeleteProduct.OnDisabledState.BorderRadius = 37;
            this.AdminDeleteProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnDisabledState.BorderThickness = 1;
            this.AdminDeleteProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminDeleteProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminDeleteProduct.OnDisabledState.IconLeftImage = null;
            this.AdminDeleteProduct.OnDisabledState.IconRightImage = null;
            this.AdminDeleteProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.onHoverState.BorderRadius = 37;
            this.AdminDeleteProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.onHoverState.BorderThickness = 1;
            this.AdminDeleteProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminDeleteProduct.onHoverState.IconLeftImage = null;
            this.AdminDeleteProduct.onHoverState.IconRightImage = null;
            this.AdminDeleteProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnIdleState.BorderRadius = 37;
            this.AdminDeleteProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnIdleState.BorderThickness = 1;
            this.AdminDeleteProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.OnIdleState.IconLeftImage = null;
            this.AdminDeleteProduct.OnIdleState.IconRightImage = null;
            this.AdminDeleteProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnPressedState.BorderRadius = 37;
            this.AdminDeleteProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminDeleteProduct.OnPressedState.BorderThickness = 1;
            this.AdminDeleteProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminDeleteProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminDeleteProduct.OnPressedState.IconLeftImage = null;
            this.AdminDeleteProduct.OnPressedState.IconRightImage = null;
            this.AdminDeleteProduct.Size = new System.Drawing.Size(85, 36);
            this.AdminDeleteProduct.TabIndex = 67;
            this.AdminDeleteProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminDeleteProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminDeleteProduct.TextMarginLeft = 0;
            this.AdminDeleteProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminDeleteProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminAddProduct
            // 
            this.AdminAddProduct.AllowAnimations = true;
            this.AdminAddProduct.AllowMouseEffects = true;
            this.AdminAddProduct.AllowToggling = false;
            this.AdminAddProduct.AnimationSpeed = 200;
            this.AdminAddProduct.AutoGenerateColors = false;
            this.AdminAddProduct.AutoRoundBorders = false;
            this.AdminAddProduct.AutoSizeLeftIcon = true;
            this.AdminAddProduct.AutoSizeRightIcon = true;
            this.AdminAddProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminAddProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminAddProduct.BackgroundImage")));
            this.AdminAddProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.ButtonText = "ADD";
            this.AdminAddProduct.ButtonTextMarginLeft = 0;
            this.AdminAddProduct.ColorContrastOnClick = 45;
            this.AdminAddProduct.ColorContrastOnHover = 45;
            this.AdminAddProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.AdminAddProduct.CustomizableEdges = borderEdges7;
            this.AdminAddProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminAddProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminAddProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminAddProduct.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.IconLeft = null;
            this.AdminAddProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminAddProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminAddProduct.IconMarginLeft = 11;
            this.AdminAddProduct.IconPadding = 10;
            this.AdminAddProduct.IconRight = null;
            this.AdminAddProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminAddProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminAddProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminAddProduct.IconSize = 25;
            this.AdminAddProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.IdleBorderRadius = 37;
            this.AdminAddProduct.IdleBorderThickness = 1;
            this.AdminAddProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.IdleIconLeftImage = null;
            this.AdminAddProduct.IdleIconRightImage = null;
            this.AdminAddProduct.IndicateFocus = false;
            this.AdminAddProduct.Location = new System.Drawing.Point(646, 467);
            this.AdminAddProduct.Name = "AdminAddProduct";
            this.AdminAddProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminAddProduct.OnDisabledState.BorderRadius = 37;
            this.AdminAddProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnDisabledState.BorderThickness = 1;
            this.AdminAddProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminAddProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminAddProduct.OnDisabledState.IconLeftImage = null;
            this.AdminAddProduct.OnDisabledState.IconRightImage = null;
            this.AdminAddProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.onHoverState.BorderRadius = 37;
            this.AdminAddProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.onHoverState.BorderThickness = 1;
            this.AdminAddProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminAddProduct.onHoverState.IconLeftImage = null;
            this.AdminAddProduct.onHoverState.IconRightImage = null;
            this.AdminAddProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnIdleState.BorderRadius = 37;
            this.AdminAddProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnIdleState.BorderThickness = 1;
            this.AdminAddProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.OnIdleState.IconLeftImage = null;
            this.AdminAddProduct.OnIdleState.IconRightImage = null;
            this.AdminAddProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnPressedState.BorderRadius = 37;
            this.AdminAddProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminAddProduct.OnPressedState.BorderThickness = 1;
            this.AdminAddProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminAddProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminAddProduct.OnPressedState.IconLeftImage = null;
            this.AdminAddProduct.OnPressedState.IconRightImage = null;
            this.AdminAddProduct.Size = new System.Drawing.Size(85, 36);
            this.AdminAddProduct.TabIndex = 66;
            this.AdminAddProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminAddProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminAddProduct.TextMarginLeft = 0;
            this.AdminAddProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminAddProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminFillEmployeeGender
            // 
            this.AdminFillEmployeeGender.AcceptsReturn = false;
            this.AdminFillEmployeeGender.AcceptsTab = false;
            this.AdminFillEmployeeGender.AnimationSpeed = 200;
            this.AdminFillEmployeeGender.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillEmployeeGender.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillEmployeeGender.AutoSizeHeight = true;
            this.AdminFillEmployeeGender.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillEmployeeGender.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillEmployeeGender.BackgroundImage")));
            this.AdminFillEmployeeGender.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillEmployeeGender.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillEmployeeGender.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillEmployeeGender.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillEmployeeGender.BorderRadius = 1;
            this.AdminFillEmployeeGender.BorderThickness = 1;
            this.AdminFillEmployeeGender.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.AdminFillEmployeeGender.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillEmployeeGender.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillEmployeeGender.DefaultText = "";
            this.AdminFillEmployeeGender.FillColor = System.Drawing.Color.White;
            this.AdminFillEmployeeGender.HideSelection = true;
            this.AdminFillEmployeeGender.IconLeft = null;
            this.AdminFillEmployeeGender.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.IconPadding = 10;
            this.AdminFillEmployeeGender.IconRight = null;
            this.AdminFillEmployeeGender.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillEmployeeGender.Lines = new string[0];
            this.AdminFillEmployeeGender.Location = new System.Drawing.Point(646, 338);
            this.AdminFillEmployeeGender.MaxLength = 32767;
            this.AdminFillEmployeeGender.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillEmployeeGender.Modified = false;
            this.AdminFillEmployeeGender.Multiline = false;
            this.AdminFillEmployeeGender.Name = "AdminFillEmployeeGender";
            stateProperties21.BorderColor = System.Drawing.Color.Transparent;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Transparent;
            stateProperties22.FillColor = System.Drawing.Color.Transparent;
            stateProperties22.ForeColor = System.Drawing.Color.Transparent;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillEmployeeGender.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Transparent;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillEmployeeGender.OnIdleState = stateProperties24;
            this.AdminFillEmployeeGender.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillEmployeeGender.PasswordChar = '\0';
            this.AdminFillEmployeeGender.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillEmployeeGender.PlaceholderText = "Fill your Employee\'s Gender";
            this.AdminFillEmployeeGender.ReadOnly = false;
            this.AdminFillEmployeeGender.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillEmployeeGender.SelectedText = "";
            this.AdminFillEmployeeGender.SelectionLength = 0;
            this.AdminFillEmployeeGender.SelectionStart = 0;
            this.AdminFillEmployeeGender.ShortcutsEnabled = true;
            this.AdminFillEmployeeGender.Size = new System.Drawing.Size(201, 37);
            this.AdminFillEmployeeGender.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillEmployeeGender.TabIndex = 65;
            this.AdminFillEmployeeGender.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillEmployeeGender.TextMarginBottom = 0;
            this.AdminFillEmployeeGender.TextMarginLeft = 3;
            this.AdminFillEmployeeGender.TextMarginTop = 0;
            this.AdminFillEmployeeGender.TextPlaceholder = "Fill your Employee\'s Gender";
            this.AdminFillEmployeeGender.UseSystemPasswordChar = false;
            this.AdminFillEmployeeGender.WordWrap = true;
            // 
            // AdminFillProductPrice
            // 
            this.AdminFillProductPrice.AcceptsReturn = false;
            this.AdminFillProductPrice.AcceptsTab = false;
            this.AdminFillProductPrice.AnimationSpeed = 200;
            this.AdminFillProductPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductPrice.AutoSizeHeight = true;
            this.AdminFillProductPrice.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductPrice.BackgroundImage")));
            this.AdminFillProductPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductPrice.BorderRadius = 1;
            this.AdminFillProductPrice.BorderThickness = 1;
            this.AdminFillProductPrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.AdminFillProductPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductPrice.DefaultText = "";
            this.AdminFillProductPrice.FillColor = System.Drawing.Color.White;
            this.AdminFillProductPrice.HideSelection = true;
            this.AdminFillProductPrice.IconLeft = null;
            this.AdminFillProductPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.IconPadding = 10;
            this.AdminFillProductPrice.IconRight = null;
            this.AdminFillProductPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductPrice.Lines = new string[0];
            this.AdminFillProductPrice.Location = new System.Drawing.Point(646, 381);
            this.AdminFillProductPrice.MaxLength = 32767;
            this.AdminFillProductPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductPrice.Modified = false;
            this.AdminFillProductPrice.Multiline = false;
            this.AdminFillProductPrice.Name = "AdminFillProductPrice";
            stateProperties25.BorderColor = System.Drawing.Color.Transparent;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Transparent;
            stateProperties26.FillColor = System.Drawing.Color.Transparent;
            stateProperties26.ForeColor = System.Drawing.Color.Transparent;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductPrice.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Transparent;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductPrice.OnIdleState = stateProperties28;
            this.AdminFillProductPrice.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductPrice.PasswordChar = '\0';
            this.AdminFillProductPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductPrice.PlaceholderText = "Fill your Product\'s Price\r\n";
            this.AdminFillProductPrice.ReadOnly = false;
            this.AdminFillProductPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductPrice.SelectedText = "";
            this.AdminFillProductPrice.SelectionLength = 0;
            this.AdminFillProductPrice.SelectionStart = 0;
            this.AdminFillProductPrice.ShortcutsEnabled = true;
            this.AdminFillProductPrice.Size = new System.Drawing.Size(201, 37);
            this.AdminFillProductPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductPrice.TabIndex = 64;
            this.AdminFillProductPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductPrice.TextMarginBottom = 0;
            this.AdminFillProductPrice.TextMarginLeft = 3;
            this.AdminFillProductPrice.TextMarginTop = 0;
            this.AdminFillProductPrice.TextPlaceholder = "Fill your Product\'s Price\r\n";
            this.AdminFillProductPrice.UseSystemPasswordChar = false;
            this.AdminFillProductPrice.WordWrap = true;
            // 
            // AdminFillProductAvailable
            // 
            this.AdminFillProductAvailable.AcceptsReturn = false;
            this.AdminFillProductAvailable.AcceptsTab = false;
            this.AdminFillProductAvailable.AnimationSpeed = 200;
            this.AdminFillProductAvailable.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductAvailable.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductAvailable.AutoSizeHeight = true;
            this.AdminFillProductAvailable.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductAvailable.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductAvailable.BackgroundImage")));
            this.AdminFillProductAvailable.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductAvailable.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductAvailable.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductAvailable.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductAvailable.BorderRadius = 1;
            this.AdminFillProductAvailable.BorderThickness = 1;
            this.AdminFillProductAvailable.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.AdminFillProductAvailable.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductAvailable.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductAvailable.DefaultText = "";
            this.AdminFillProductAvailable.FillColor = System.Drawing.Color.White;
            this.AdminFillProductAvailable.HideSelection = true;
            this.AdminFillProductAvailable.IconLeft = null;
            this.AdminFillProductAvailable.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.IconPadding = 10;
            this.AdminFillProductAvailable.IconRight = null;
            this.AdminFillProductAvailable.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductAvailable.Lines = new string[0];
            this.AdminFillProductAvailable.Location = new System.Drawing.Point(646, 424);
            this.AdminFillProductAvailable.MaxLength = 32767;
            this.AdminFillProductAvailable.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductAvailable.Modified = false;
            this.AdminFillProductAvailable.Multiline = false;
            this.AdminFillProductAvailable.Name = "AdminFillProductAvailable";
            stateProperties29.BorderColor = System.Drawing.Color.Transparent;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Transparent;
            stateProperties30.FillColor = System.Drawing.Color.Transparent;
            stateProperties30.ForeColor = System.Drawing.Color.Transparent;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductAvailable.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Transparent;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductAvailable.OnIdleState = stateProperties32;
            this.AdminFillProductAvailable.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductAvailable.PasswordChar = '\0';
            this.AdminFillProductAvailable.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductAvailable.PlaceholderText = "Fill your Product\'s Available\r\n";
            this.AdminFillProductAvailable.ReadOnly = false;
            this.AdminFillProductAvailable.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductAvailable.SelectedText = "";
            this.AdminFillProductAvailable.SelectionLength = 0;
            this.AdminFillProductAvailable.SelectionStart = 0;
            this.AdminFillProductAvailable.ShortcutsEnabled = true;
            this.AdminFillProductAvailable.Size = new System.Drawing.Size(201, 37);
            this.AdminFillProductAvailable.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductAvailable.TabIndex = 63;
            this.AdminFillProductAvailable.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductAvailable.TextMarginBottom = 0;
            this.AdminFillProductAvailable.TextMarginLeft = 3;
            this.AdminFillProductAvailable.TextMarginTop = 0;
            this.AdminFillProductAvailable.TextPlaceholder = "Fill your Product\'s Available\r\n";
            this.AdminFillProductAvailable.UseSystemPasswordChar = false;
            this.AdminFillProductAvailable.WordWrap = true;
            // 
            // AdminFillProductType
            // 
            this.AdminFillProductType.AcceptsReturn = false;
            this.AdminFillProductType.AcceptsTab = false;
            this.AdminFillProductType.AnimationSpeed = 200;
            this.AdminFillProductType.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductType.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductType.AutoSizeHeight = true;
            this.AdminFillProductType.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductType.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductType.BackgroundImage")));
            this.AdminFillProductType.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductType.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductType.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductType.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductType.BorderRadius = 1;
            this.AdminFillProductType.BorderThickness = 1;
            this.AdminFillProductType.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.AdminFillProductType.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductType.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductType.DefaultText = "";
            this.AdminFillProductType.FillColor = System.Drawing.Color.White;
            this.AdminFillProductType.HideSelection = true;
            this.AdminFillProductType.IconLeft = null;
            this.AdminFillProductType.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.IconPadding = 10;
            this.AdminFillProductType.IconRight = null;
            this.AdminFillProductType.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductType.Lines = new string[0];
            this.AdminFillProductType.Location = new System.Drawing.Point(646, 295);
            this.AdminFillProductType.MaxLength = 32767;
            this.AdminFillProductType.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductType.Modified = false;
            this.AdminFillProductType.Multiline = false;
            this.AdminFillProductType.Name = "AdminFillProductType";
            stateProperties33.BorderColor = System.Drawing.Color.Transparent;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Transparent;
            stateProperties34.FillColor = System.Drawing.Color.Transparent;
            stateProperties34.ForeColor = System.Drawing.Color.Transparent;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductType.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Transparent;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductType.OnIdleState = stateProperties36;
            this.AdminFillProductType.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductType.PasswordChar = '\0';
            this.AdminFillProductType.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductType.PlaceholderText = "Fill your Product\'s  Type\r\n";
            this.AdminFillProductType.ReadOnly = false;
            this.AdminFillProductType.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductType.SelectedText = "";
            this.AdminFillProductType.SelectionLength = 0;
            this.AdminFillProductType.SelectionStart = 0;
            this.AdminFillProductType.ShortcutsEnabled = true;
            this.AdminFillProductType.Size = new System.Drawing.Size(201, 37);
            this.AdminFillProductType.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductType.TabIndex = 62;
            this.AdminFillProductType.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductType.TextMarginBottom = 0;
            this.AdminFillProductType.TextMarginLeft = 3;
            this.AdminFillProductType.TextMarginTop = 0;
            this.AdminFillProductType.TextPlaceholder = "Fill your Product\'s  Type\r\n";
            this.AdminFillProductType.UseSystemPasswordChar = false;
            this.AdminFillProductType.WordWrap = true;
            // 
            // AdminFillProductName
            // 
            this.AdminFillProductName.AcceptsReturn = false;
            this.AdminFillProductName.AcceptsTab = false;
            this.AdminFillProductName.AnimationSpeed = 200;
            this.AdminFillProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.AdminFillProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.AdminFillProductName.AutoSizeHeight = true;
            this.AdminFillProductName.BackColor = System.Drawing.Color.Transparent;
            this.AdminFillProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminFillProductName.BackgroundImage")));
            this.AdminFillProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.AdminFillProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminFillProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.AdminFillProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.AdminFillProductName.BorderRadius = 1;
            this.AdminFillProductName.BorderThickness = 1;
            this.AdminFillProductName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.AdminFillProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.AdminFillProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.AdminFillProductName.DefaultText = "";
            this.AdminFillProductName.FillColor = System.Drawing.Color.White;
            this.AdminFillProductName.HideSelection = true;
            this.AdminFillProductName.IconLeft = null;
            this.AdminFillProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.IconPadding = 10;
            this.AdminFillProductName.IconRight = null;
            this.AdminFillProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.AdminFillProductName.Lines = new string[0];
            this.AdminFillProductName.Location = new System.Drawing.Point(646, 210);
            this.AdminFillProductName.MaxLength = 32767;
            this.AdminFillProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.AdminFillProductName.Modified = false;
            this.AdminFillProductName.Multiline = false;
            this.AdminFillProductName.Name = "AdminFillProductName";
            stateProperties37.BorderColor = System.Drawing.Color.Transparent;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Transparent;
            stateProperties38.FillColor = System.Drawing.Color.Transparent;
            stateProperties38.ForeColor = System.Drawing.Color.Transparent;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.AdminFillProductName.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.Transparent;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.AdminFillProductName.OnIdleState = stateProperties40;
            this.AdminFillProductName.Padding = new System.Windows.Forms.Padding(3);
            this.AdminFillProductName.PasswordChar = '\0';
            this.AdminFillProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.AdminFillProductName.PlaceholderText = "Fill your Product\'s Name\r\n";
            this.AdminFillProductName.ReadOnly = false;
            this.AdminFillProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.AdminFillProductName.SelectedText = "";
            this.AdminFillProductName.SelectionLength = 0;
            this.AdminFillProductName.SelectionStart = 0;
            this.AdminFillProductName.ShortcutsEnabled = true;
            this.AdminFillProductName.Size = new System.Drawing.Size(201, 37);
            this.AdminFillProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.AdminFillProductName.TabIndex = 61;
            this.AdminFillProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.AdminFillProductName.TextMarginBottom = 0;
            this.AdminFillProductName.TextMarginLeft = 3;
            this.AdminFillProductName.TextMarginTop = 0;
            this.AdminFillProductName.TextPlaceholder = "Fill your Product\'s Name\r\n";
            this.AdminFillProductName.UseSystemPasswordChar = false;
            this.AdminFillProductName.WordWrap = true;
            // 
            // AdminCheckProduct
            // 
            this.AdminCheckProduct.AllowAnimations = true;
            this.AdminCheckProduct.AllowMouseEffects = true;
            this.AdminCheckProduct.AllowToggling = false;
            this.AdminCheckProduct.AnimationSpeed = 200;
            this.AdminCheckProduct.AutoGenerateColors = false;
            this.AdminCheckProduct.AutoRoundBorders = false;
            this.AdminCheckProduct.AutoSizeLeftIcon = true;
            this.AdminCheckProduct.AutoSizeRightIcon = true;
            this.AdminCheckProduct.BackColor = System.Drawing.Color.Transparent;
            this.AdminCheckProduct.BackColor1 = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AdminCheckProduct.BackgroundImage")));
            this.AdminCheckProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.ButtonText = "CHECK";
            this.AdminCheckProduct.ButtonTextMarginLeft = 0;
            this.AdminCheckProduct.ColorContrastOnClick = 45;
            this.AdminCheckProduct.ColorContrastOnHover = 45;
            this.AdminCheckProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.AdminCheckProduct.CustomizableEdges = borderEdges8;
            this.AdminCheckProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AdminCheckProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AdminCheckProduct.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AdminCheckProduct.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.IconLeft = null;
            this.AdminCheckProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AdminCheckProduct.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AdminCheckProduct.IconMarginLeft = 11;
            this.AdminCheckProduct.IconPadding = 10;
            this.AdminCheckProduct.IconRight = null;
            this.AdminCheckProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AdminCheckProduct.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AdminCheckProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AdminCheckProduct.IconSize = 25;
            this.AdminCheckProduct.IdleBorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.IdleBorderRadius = 37;
            this.AdminCheckProduct.IdleBorderThickness = 1;
            this.AdminCheckProduct.IdleFillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.IdleIconLeftImage = null;
            this.AdminCheckProduct.IdleIconRightImage = null;
            this.AdminCheckProduct.IndicateFocus = false;
            this.AdminCheckProduct.Location = new System.Drawing.Point(646, 253);
            this.AdminCheckProduct.Name = "AdminCheckProduct";
            this.AdminCheckProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AdminCheckProduct.OnDisabledState.BorderRadius = 37;
            this.AdminCheckProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnDisabledState.BorderThickness = 1;
            this.AdminCheckProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AdminCheckProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AdminCheckProduct.OnDisabledState.IconLeftImage = null;
            this.AdminCheckProduct.OnDisabledState.IconRightImage = null;
            this.AdminCheckProduct.onHoverState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.onHoverState.BorderRadius = 37;
            this.AdminCheckProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.onHoverState.BorderThickness = 1;
            this.AdminCheckProduct.onHoverState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.AdminCheckProduct.onHoverState.IconLeftImage = null;
            this.AdminCheckProduct.onHoverState.IconRightImage = null;
            this.AdminCheckProduct.OnIdleState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnIdleState.BorderRadius = 37;
            this.AdminCheckProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnIdleState.BorderThickness = 1;
            this.AdminCheckProduct.OnIdleState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.OnIdleState.IconLeftImage = null;
            this.AdminCheckProduct.OnIdleState.IconRightImage = null;
            this.AdminCheckProduct.OnPressedState.BorderColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnPressedState.BorderRadius = 37;
            this.AdminCheckProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AdminCheckProduct.OnPressedState.BorderThickness = 1;
            this.AdminCheckProduct.OnPressedState.FillColor = System.Drawing.Color.LightSalmon;
            this.AdminCheckProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AdminCheckProduct.OnPressedState.IconLeftImage = null;
            this.AdminCheckProduct.OnPressedState.IconRightImage = null;
            this.AdminCheckProduct.Size = new System.Drawing.Size(201, 36);
            this.AdminCheckProduct.TabIndex = 60;
            this.AdminCheckProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AdminCheckProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AdminCheckProduct.TextMarginLeft = 0;
            this.AdminCheckProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.AdminCheckProduct.UseDefaultRadiusAndThickness = true;
            // 
            // AdminProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.dataGridView1);
            this.Controls.Add(this.AdminUpdateProduct);
            this.Controls.Add(this.AdminDeleteProduct);
            this.Controls.Add(this.AdminAddProduct);
            this.Controls.Add(this.AdminFillEmployeeGender);
            this.Controls.Add(this.AdminFillProductPrice);
            this.Controls.Add(this.AdminFillProductAvailable);
            this.Controls.Add(this.AdminFillProductType);
            this.Controls.Add(this.AdminFillProductName);
            this.Controls.Add(this.AdminCheckProduct);
            this.Name = "AdminProduct";
            this.Size = new System.Drawing.Size(1037, 761);
            this.Load += new System.EventHandler(this.AdminProduct_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.DataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminUpdateProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminDeleteProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminAddProduct;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillEmployeeGender;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductPrice;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductAvailable;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductType;
        private Bunifu.UI.WinForms.BunifuTextBox AdminFillProductName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AdminCheckProduct;
    }
}
